/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Conexion.DAO;
import Decoracion.RedimensionarImagen;
import FramePrincipal.Logueo;
import Pojo.CatalogoExamen;
import Pojo.DetalleFactpro;
import Pojo.DetalleFacturaEx;
import Pojo.FacturaConsulta;
//import Pojo.DetalleFactura;
import Pojo.FacturaExamen;
import Pojo.Paciente;
//import Pojo.FacturaProcedimiento;
import Pojo.ProcedimientosEspeciales;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;

/**
 *
 * @author HOME
 */
public class FacturaExt extends javax.swing.JInternalFrame {

    /**
     * Creates new form FacturaExt
     */
    SessionFactory s;
    float t=0;
    DecimalFormat df = new DecimalFormat("0.0"); 
    String cajeronombre, cajeroapellido;
    int idcajero=-1;
    public FacturaExt(SessionFactory sf) {
        
            initComponents();
            s= sf;
            DAO d = new DAO(s);
            List<FacturaExamen> listafex = d.ListarFacturaExamen();
            List<FacturaConsulta> listfactc = d.ListarFacturaConsulta();
            int num = listafex.size()+ listfactc.size() +1;
            this.n0factura.setText(String.valueOf(num));
            
            //Obtener id del cajero
            idcajero= Integer.parseInt(Logueo.getUser().substring(6));
            DefaultTableModel dft = new DefaultTableModel();
            dft.addColumn("Nombre");dft.addColumn("Precio");
            this.jTable1.setModel(dft);
            
            Pojo.Cajero c = d.busquedaCajeroId(idcajero);
            if(c==null){JOptionPane.showMessageDialog(this,"No hay cajeros disponibles","Error",JOptionPane.ERROR_MESSAGE);}
            else{
                try {
                    InputStream in = new ByteArrayInputStream(c.getFoto());
                    BufferedImage image = ImageIO.read(in);
                    CargarFoto(new ImageIcon(image));
                    cajeronombre=c.getNombre(); cajeroapellido= c.getApellido();
                    this.namecajero.setText(c.getNombre()+" "+c.getApellido());
                } catch (IOException ex) {
                    Logger.getLogger(FacturaExt.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.totaltextfield.setText(String.valueOf(t));
            }
            
            
            Date fch = new Date();
            SimpleDateFormat sfd = new SimpleDateFormat("dd-MM-yyyy");
            this.fechalbl.setText(sfd.format(fch));
        
            LlenarExamenes();
            LlenarProcedimientos();
            }   
    
    
    
    public void LlenarExamenes(){
    DAO d = new DAO(s);
    DefaultListModel dfl = new DefaultListModel();
   List<CatalogoExamen> lista = d.Listar_CatalogoExamen();
   for(CatalogoExamen c:lista){
       dfl.addElement(c.getNombre());
   }
   this.jList1.setModel(dfl);
    }
    
    
    
     public void LlenarProcedimientos(){
    DAO d = new DAO(s);
    DefaultListModel dfl = new DefaultListModel();
   List<ProcedimientosEspeciales> lista = d.Listar_ProcedimientosEspeciales();
   for(ProcedimientosEspeciales c:lista){
       dfl.addElement(c.getNombre());
   }
   this.jList3.setModel(dfl);
    }
    
      public void CargarFoto(Icon icono){
        RedimensionarImagen redimImagen = new RedimensionarImagen();
        icono = redimImagen.imageToIcon(redimImagen.iconToBufferedImage(icono).getScaledInstance(190, 125, 0));
        this.lblimage.setIcon(icono);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechalbl = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        n0factura = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        namecajero = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totaltextfield = new javax.swing.JTextField();
        pagotextfield = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        cambiotextfield = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setClosable(true);
        setTitle("Facturar");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion general"));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Fecha: ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Cajero :");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("No. Paciente :");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("No. Factura:");

        fechalbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        n0factura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dolar", "Cordoba" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Tipo de moneda:");

        namecajero.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        lblimage.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(n0factura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechalbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(namecajero, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(n0factura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(namecajero, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(fechalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examenes y Procedimientos Especiales Disponibles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        jScrollPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList3);

        jPanel1.add(jScrollPane3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );

        jButton3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton3.setText("Agregar Procedimiento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Total:");

        jButton4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save (1).png"))); // NOI18N
        jButton4.setText("Guardar Factura");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Pago:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("Cambio");

        totaltextfield.setEditable(false);
        totaltextfield.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        totaltextfield.setText("0");

        pagotextfield.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        pagotextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pagotextfieldFocusLost(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton5.setText("Quitar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cambiotextfield.setEditable(false);
        cambiotextfield.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cambiotextfield.setText("0");

        jButton6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton6.setText("Agregar Examen");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cambiotextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagotextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaltextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pagotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cambiotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       DefaultTableModel dft = (DefaultTableModel) this.jTable1.getModel();
       DAO d = new DAO(s);
       String vl1=String.valueOf(this.jList3.getSelectedValue());
       
           List<ProcedimientosEspeciales> lista =d.Listar_ProcedimientosEspeciales();
           for(ProcedimientosEspeciales e: lista){
               if(e.getNombre().equals(vl1)){
               String vector[]={e.getNombre(),String.valueOf(e.getPrecio())};
               this.totaltextfield.setText(String.valueOf(e.getPrecio()+ Float.parseFloat(this.totaltextfield.getText())));
               dft.addRow(vector);
               vector=null;
               
       this.jTable1.setModel(dft);
               }
       }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       int index = this.jTable1.getSelectedRow();
       if(index==-1){JOptionPane.showMessageDialog(this, "Seleccione una fila de la tabla Detalles","Error",JOptionPane.ERROR_MESSAGE);}
       else{
       DefaultTableModel dft = (DefaultTableModel) this.jTable1.getModel();
       
       float precio= Float.parseFloat(jTable1.getValueAt(index, 1).toString());
       float total = Float.parseFloat(this.totaltextfield.getText())-precio;
       this.totaltextfield.setText(String.valueOf(total));
       dft.removeRow(index);
       this.jTable1.setModel(dft);
       }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
     
    }//GEN-LAST:event_jTable1PropertyChange

    private void pagotextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pagotextfieldFocusLost
       try{
       float pago = Float.parseFloat(this.pagotextfield.getText());
       float total = Float.parseFloat(this.totaltextfield.getText());
       if(pago<total){JOptionPane.showMessageDialog(this, "Pago incorrecto","Error",JOptionPane.ERROR_MESSAGE);this.cambiotextfield.setText("");}
       else{
       this.cambiotextfield.setText(String.valueOf(pago-total));}
       }catch(NumberFormatException e){
       JOptionPane.showMessageDialog(this,"Dato incorrecto","Error",JOptionPane.ERROR_MESSAGE);
       this.cambiotextfield.setText("0");
       }
    }//GEN-LAST:event_pagotextfieldFocusLost

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
     
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel dft = (DefaultTableModel) this.jTable1.getModel();
       DAO d = new DAO(s);
       String vl1=String.valueOf(this.jList1.getSelectedValue());
       
           List<CatalogoExamen> lista =d.Listar_CatalogoExamen();
           for(CatalogoExamen e: lista){
               if(e.getNombre().equals(vl1)){
               String vector[]={e.getNombre(),String.valueOf(e.getPrecio())};
               this.totaltextfield.setText(String.valueOf(e.getPrecio()+ Float.parseFloat(this.totaltextfield.getText())));
               dft.addRow(vector);
               vector=null;
               
           this.jTable1.setModel(dft);
           }
       }
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
        String al = this.jTextField4.getText();
        
       if(Float.parseFloat(this.totaltextfield.getText())==0 || this.jTextField4.equals("")){
       JOptionPane.showMessageDialog(this, "Revise los datos intoducidos","Error",JOptionPane.ERROR_MESSAGE);
       }
       else{
           ComprobarPaciente();
           DAO d = new DAO(s);
           
             
           FacturaExamen fe = new FacturaExamen();
        fe.setCajero(d.busquedaCajeroId(idcajero));
        fe.setNumfactura(Integer.parseInt(n0factura.getText()));
        fe.setFecha(new Date());
        fe.setPaciente(d.busquedaPacienteId(Integer.parseInt(this.jTextField4.getText())));
        fe.setTotal(0);
        fe.setPago(0);
        fe.setCambio(0);
        int idfact = d.GuardarFacturaex(fe);   
        
           //Listar los examenes
            List<ProcedimientosEspeciales> listapro = d.Listar_ProcedimientosEspeciales();
            List<ProcedimientosEspeciales> listaprocedimientos = new ArrayList<ProcedimientosEspeciales>();
       for(int i=0; i<this.jTable1.getRowCount();i++){
       for(ProcedimientosEspeciales p: listapro){
           if(p.getNombre().equals(this.jTable1.getValueAt(i, 0))){
           listaprocedimientos.add(p);
           }
       }
       }
       
       //Listar los procedimientos
       List<CatalogoExamen> listaex = d.Listar_CatalogoExamen();
       List<CatalogoExamen> listaexamenes = new ArrayList<CatalogoExamen>();
       for(int i=0; i<this.jTable1.getRowCount();i++){
       for(CatalogoExamen p: listaex){
           if(p.getNombre().equals(this.jTable1.getValueAt(i, 0))){
           listaexamenes.add(p);
           }
       }
       }
       
       //Guardar Detalle de los examenes
       if(listaexamenes != null){
       for(CatalogoExamen q : listaexamenes){
       DetalleFacturaEx dfe = new DetalleFacturaEx();
       dfe.setCatalogoExamen(q);
       dfe.setFacturaExamen(d.busquedaFacturaExamenId(idfact));
       if(d.GuardarDetalleFacturaEx(dfe)==false){JOptionPane.showMessageDialog(this,"Error al guardar Detalle Examenes","Error",JOptionPane.ERROR_MESSAGE);break;}
       }
       }
       
       //Guardar Detalle de los procedimientos
        if(listaprocedimientos != null){
       for(ProcedimientosEspeciales q : listaprocedimientos){
       DetalleFactpro dfp = new DetalleFactpro();
       dfp.setProcedimientosEspeciales(q);
       dfp.setFacturaExamen(d.busquedaFacturaExamenId(idfact));
       if(d.GuardarDetalleFacturaPro(dfp)==false){JOptionPane.showMessageDialog(this,"Error al guardar Detalle Procedimientos","Error",JOptionPane.ERROR_MESSAGE); break;}
       }
       }
       
        FacturaExamen fea = d.busquedaFacturaExamenId(idfact);
        fea.setTotal(Float.parseFloat(totaltextfield.getText()));
        fea.setPago(Float.parseFloat(pagotextfield.getText()));
        fea.setCambio(Float.parseFloat(cambiotextfield.getText()));
        if(d.ActualizarFacturaExamen(fea)==true){JOptionPane.showMessageDialog(this, "Factura Guardada"); Limpiar();}   
        else{JOptionPane.showMessageDialog(this, "Error al guardar Factura revise los datos","Error",JOptionPane.ERROR_MESSAGE);}
       }
       }catch(NumberFormatException ee){JOptionPane.showMessageDialog(this, "Dato incorrecto en el numero de paciente, introduzca un número");}
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FacturaExt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cambiotextfield;
    private javax.swing.JLabel fechalbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel n0factura;
    private javax.swing.JLabel namecajero;
    private javax.swing.JTextField pagotextfield;
    private javax.swing.JTextField totaltextfield;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        FacturaExt c = new FacturaExt(s);
       this.getDesktopPane().add(c);
       c.setVisible(true);
        this.dispose();
    }

    private boolean ComprobarPaciente() {
    DAO d = new DAO(s);
    Paciente p = d.busquedaPacienteId(Integer.parseInt(this.jTextField4.getText()));
    if(p == null){return false;}
    else{return true;}
    }
}
