/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Conexion.DAO;
import Decoracion.RedimensionarImagen;
import FramePrincipal.Logueo;
import Pojo.Consulta;
import Pojo.FacturaConsulta;
import Pojo.FacturaExamen;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.hibernate.SessionFactory;

/**
 *
 * @author HOME
 */
public class FacturaCons extends javax.swing.JInternalFrame {

    /**
     * Creates new form FacturaConsulta
     */
    SessionFactory sf ;
    int idcajero=-1;
    String cajeronombre, cajeroapellido;
    float t=0;
    DecimalFormat df = new DecimalFormat("0.0"); 
    
    public FacturaCons(SessionFactory s) {
        initComponents();
       sf=s;
            DAO d = new DAO(sf);
            List<FacturaExamen> listafex = d.ListarFacturaExamen();
            List<FacturaConsulta> listfactc = d.ListarFacturaConsulta();
            int num = listafex.size()+ listfactc.size() +1;
            this.n0factura.setText(String.valueOf(num));
            
            //Obtener id del cajero
            idcajero= Integer.parseInt(Logueo.getUser().substring(6));
            
            Pojo.Cajero c = d.busquedaCajeroId(idcajero);
            if(c==null){JOptionPane.showMessageDialog(this,"No hay cajeros disponibles","Error",JOptionPane.ERROR_MESSAGE);}
            else{
                try {
                    InputStream in = new ByteArrayInputStream(c.getFoto());
                    BufferedImage image = ImageIO.read(in);
                    CargarFoto(new ImageIcon(image));
                    cajeronombre=c.getNombre(); cajeroapellido= c.getApellido();
                    this.namecajero.setText(c.getNombre()+" "+c.getApellido());
                } catch (IOException ex) {
                    Logger.getLogger(FacturaExt.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            
            Date fch = new Date();
            SimpleDateFormat sfd = new SimpleDateFormat("dd-MM-yyyy");
            this.fechalbl.setText(sfd.format(fch));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechalbl = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        n0factura = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        namecajero = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cambiotextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pagotextfield = new javax.swing.JTextField();
        totaltextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Facurar Consulta");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion general"));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Fecha: ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Cajero :");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("No. Consulta :");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("No. Factura:");

        fechalbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        n0factura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dolar", "Cordoba" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Tipo de moneda:");

        namecajero.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        lblimage.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(n0factura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechalbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(namecajero, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(n0factura, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(namecajero, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(fechalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jButton4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save (1).png"))); // NOI18N
        jButton4.setText("Guardar Factura");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cambiotextfield.setEditable(false);
        cambiotextfield.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cambiotextfield.setText("0");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Cambio");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Pago:");

        pagotextfield.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        pagotextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pagotextfieldFocusLost(evt);
            }
        });

        totaltextfield.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cambiotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(pagotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(totaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pagotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cambiotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jButton4)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void pagotextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pagotextfieldFocusLost
        try{
            float pago = Float.parseFloat(this.pagotextfield.getText());
            float total = Float.parseFloat(this.totaltextfield.getText());
            if(pago<total){JOptionPane.showMessageDialog(this, "Pago incorrecto","Error",JOptionPane.ERROR_MESSAGE);this.cambiotextfield.setText("");}
            else{
                this.cambiotextfield.setText(String.valueOf(pago-total));}
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Dato incorrecto","Error",JOptionPane.ERROR_MESSAGE);
            this.cambiotextfield.setText("0");
        }
    }//GEN-LAST:event_pagotextfieldFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            String al = this.jTextField4.getText();

            if(Float.parseFloat(this.totaltextfield.getText())==0 || this.jTextField4.equals("")){
                JOptionPane.showMessageDialog(this, "Revise los datos intoducidos","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                ComprobarConsulta();
                DAO d = new DAO(sf);
                FacturaConsulta fc = new FacturaConsulta();
                fc.setNumfactura(Integer.parseInt(this.n0factura.getText()));
                fc.setFecha(new Date());
                fc.setConsulta(d.busquedaConsultaId(Integer.parseInt(this.jTextField4.getText())));
                fc.setCajero(d.busquedaCajeroId(idcajero));
                fc.setTotal(Float.parseFloat(this.totaltextfield.getText()));
                fc.setPago(Float.parseFloat(this.pagotextfield.getText()));
                fc.setCambio(Float.parseFloat(this.cambiotextfield.getText()));
                int i =d.GuardarFacturaConsulta(fc);
                if(i!=-1){JOptionPane.showMessageDialog(this,"Facutra Registrada");Limpiar();}
                else{JOptionPane.showMessageDialog(this, "Error","Error al guardar Factura",JOptionPane.ERROR_MESSAGE);}
                }
        }catch(NumberFormatException ee){JOptionPane.showMessageDialog(this, "Dato incorrecto en el numero de paciente, introduzca un número");}

    }//GEN-LAST:event_jButton4ActionPerformed

 public void CargarFoto(Icon icono){
        RedimensionarImagen redimImagen = new RedimensionarImagen();
        icono = redimImagen.imageToIcon(redimImagen.iconToBufferedImage(icono).getScaledInstance(190, 125, 0));
        this.lblimage.setIcon(icono);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cambiotextfield;
    private javax.swing.JLabel fechalbl;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel n0factura;
    private javax.swing.JLabel namecajero;
    private javax.swing.JTextField pagotextfield;
    private javax.swing.JTextField totaltextfield;
    // End of variables declaration//GEN-END:variables

    
    private void Limpiar() {
        FacturaCons c = new FacturaCons(sf);
       this.getDesktopPane().add(c);
       c.setVisible(true);
        this.dispose();
    }

    private boolean ComprobarConsulta() {
    DAO d = new DAO(sf);
    Consulta p = d.busquedaConsultaId(Integer.parseInt(this.jTextField4.getText()));
    if(p == null){return false;}
    else{return true;}
    }
}
