/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Conexion.DAO;
import Pojo.*;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.exolab.castor.types.Date;
import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author HOME
 */
public class VerFacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerFacturas
     */
    SessionFactory sf;
    public VerFacturas(SessionFactory s) {
        initComponents();
        sf = s;
        DefaultTableModel dft = new DefaultTableModel();
        dft.addColumn("Numero de Factura");
        dft.addColumn("Fecha");
        dft.addColumn("Total");
        dft.addColumn("Pago");
        dft.addColumn("Cambio");
        dft.addColumn("No. Paciente/Consulta");
        dft.addColumn("Cajero nombre");
        dft.addColumn("Cajero apellido");
        
        DAO d = new DAO(sf);
Session se = sf.openSession();
        Criteria cr = se.createCriteria(FacturaExamen.class);
cr.addOrder(Order.desc("fecha"));
Criteria crf = se.createCriteria(Pojo.FacturaConsulta.class);
crf.addOrder(Order.desc("fecha"));
List<Pojo.FacturaExamen> listafe = cr.list();
List<Pojo.FacturaConsulta> listafc = crf.list();
        List<Paciente> listap = d.Listar_Pacientes();
        List<Pojo.Cajero> listac = d.Listar_Cajero();
        List<Pojo.Consulta> listacons = d.Listar_Consulta();
        
        for(FacturaExamen fe : listafe){
        for(Pojo.Cajero c : listac){
        if(c.getIdCajero() == fe.getCajero().getIdCajero()){
        for(Pojo.Paciente p : listap){
        if(p.getIdPaciente() == fe.getPaciente().getIdPaciente()){
        String fila []= {String.valueOf(fe.getNumfactura()),String.valueOf( fe.getFecha()),String.valueOf(fe.getTotal()), String.valueOf(fe.getPago()),String.valueOf(fe.getCambio()), String.valueOf(p.getIdPaciente()), c.getNombre(),c.getApellido()};
        dft.addRow(fila);
        }
        }
        }
        }
        }
    
        for(FacturaConsulta fc : listafc){
        for(Pojo.Cajero c : listac){
        if(c.getIdCajero() == fc.getCajero().getIdCajero()){
        for(Pojo.Consulta co : listacons){
        if(co.getIdConsulta() == fc.getConsulta().getIdConsulta()){
        String fila []= {String.valueOf(fc.getNumfactura()),String.valueOf( fc.getFecha()),String.valueOf(fc.getTotal()), String.valueOf(fc.getPago()),String.valueOf(fc.getCambio()),String.valueOf(co.getIdConsulta()),c.getNombre(),c.getApellido()};
        dft.addRow(fila);
        }
        }
        }
        }
        }
    
        
        this.jTable1.setModel(dft);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Facturas");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1436254886_Search.png"))); // NOI18N
        jButton2.setText("Buscar Por:");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Fecha inicial");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Fecha Final");

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setText("Ver Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            java.util.Date fechai = formatoDelTexto.parse(this.jTextField2.getText());
            java.util.Date fechaf= formatoDelTexto.parse(this.jTextField3.getText());
            
            
                
                Session s = sf.openSession();
                DAO d=  new DAO(sf);
                DefaultTableModel dft = new DefaultTableModel();
                Criteria cr = s.createCriteria(FacturaExamen.class);
                cr.add(Restrictions.between("fecha",fechai,fechaf));
                Criteria crf = s.createCriteria(Pojo.FacturaConsulta.class);
                crf.add(Restrictions.between("fecha",fechai,fechaf));
                List<Pojo.FacturaExamen> listafe = cr.list();
                List<Pojo.FacturaConsulta> listafc = crf.list();
                List<Paciente> listap = d.Listar_Pacientes();
                List<Pojo.Cajero> listac = d.Listar_Cajero();
                List<Pojo.Consulta> listacons = d.Listar_Consulta();
                
                for(FacturaExamen fe : listafe){
                    for(Pojo.Cajero c : listac){
                        if(c.getIdCajero() == fe.getCajero().getIdCajero()){
                            for(Pojo.Paciente p : listap){
                                if(p.getIdPaciente() == fe.getPaciente().getIdPaciente()){
                                    String fila []= {String.valueOf(fe.getNumfactura()),String.valueOf( fe.getFecha()),String.valueOf(fe.getTotal()), String.valueOf(fe.getPago()),String.valueOf(fe.getCambio()), String.valueOf(p.getIdPaciente()), c.getNombre(),c.getApellido()};
                                    dft.addRow(fila);
                                }
                            }
                        }
                    }
                }
                
                for(FacturaConsulta fc : listafc){
                    for(Pojo.Cajero c : listac){
                        if(c.getIdCajero() == fc.getCajero().getIdCajero()){
                            for(Pojo.Consulta co : listacons){
                                if(co.getIdConsulta() == fc.getConsulta().getIdConsulta()){
                                    String fila []= {String.valueOf(fc.getNumfactura()),String.valueOf( fc.getFecha()),String.valueOf(fc.getTotal()), String.valueOf(fc.getPago()),String.valueOf(fc.getCambio()),String.valueOf(co.getIdConsulta()),c.getNombre(),c.getApellido()};
                                    dft.addRow(fila);
                                }
                            }
                        }
                    }
                

                
                this.jTable1.setModel(dft);
                
                
                
                
            }       } catch (ParseException ex) {
            Logger.getLogger(VerFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            VerFacturas c = new VerFacturas(sf);
            this.getDesktopPane().add(c);
            c.setMaximum(true);
            c.setVisible(true);
            this.dispose();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VerFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
