/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Conexion.DAO;
import Pojo.*;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.exolab.castor.types.Date;
import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author HOME
 */
public class VerFacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerFacturas
     */
    SessionFactory sf;
    public VerFacturas(SessionFactory s) {
        initComponents();
        sf = s;
        DefaultTableModel dft = new DefaultTableModel();
        dft.addColumn("Numero de Factura");
        dft.addColumn("Fecha");
        dft.addColumn("Total");
        dft.addColumn("Pago");
        dft.addColumn("Cambio");
        dft.addColumn("No. Paciente/Consulta");
        dft.addColumn("Cajero nombre");
        dft.addColumn("Cajero apellido");
        
        DAO d = new DAO(sf);
Session se = sf.openSession();
        Criteria cr = se.createCriteria(FacturaExamen.class);
cr.addOrder(Order.desc("fecha"));
Criteria crf = se.createCriteria(Pojo.FacturaConsulta.class);
crf.addOrder(Order.desc("fecha"));
List<Pojo.FacturaExamen> listafe = cr.list();
List<Pojo.FacturaConsulta> listafc = crf.list();
        List<Paciente> listap = d.Listar_Pacientes();
        List<Pojo.Cajero> listac = d.Listar_Cajero();
        List<Pojo.Consulta> listacons = d.Listar_Consulta();
        
        for(FacturaExamen fe : listafe){
        for(Pojo.Cajero c : listac){
        if(c.getIdCajero() == fe.getCajero().getIdCajero()){
        for(Pojo.Paciente p : listap){
        if(p.getIdPaciente() == fe.getPaciente().getIdPaciente()){
        String fila []= {String.valueOf(fe.getNumfactura()),String.valueOf( fe.getFecha()),String.valueOf(fe.getTotal()), String.valueOf(fe.getPago()),String.valueOf(fe.getCambio()), String.valueOf(p.getIdPaciente()), c.getNombre(),c.getApellido()};
        dft.addRow(fila);
        }
        }
        }
        }
        }
    
        for(FacturaConsulta fc : listafc){
        for(Pojo.Cajero c : listac){
        if(c.getIdCajero() == fc.getCajero().getIdCajero()){
        for(Pojo.Consulta co : listacons){
        if(co.getIdConsulta() == fc.getConsulta().getIdConsulta()){
        String fila []= {String.valueOf(fc.getNumfactura()),String.valueOf( fc.getFecha()),String.valueOf(fc.getTotal()), String.valueOf(fc.getPago()),String.valueOf(fc.getCambio()),String.valueOf(co.getIdConsulta()),c.getNombre(),c.getApellido()};
        dft.addRow(fila);
        }
        }
        }
        }
        }
    
        
        this.jTable1.setModel(dft);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("Facturas");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1436254886_Search.png"))); // NOI18N
        jButton2.setText("Buscar Por:");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Fecha inicial");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Fecha Final");

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setText("Ver Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            java.util.Date fechai = formatoDelTexto.parse(this.jTextField2.getText());
            java.util.Date fechaf= formatoDelTexto.parse(this.jTextField3.getText());
            
            
                
                Session s = sf.openSession();
                DAO d=  new DAO(sf);
                DefaultTableModel df = new DefaultTableModel();
        df.addColumn("Numero de Factura");
        df.addColumn("Fecha");
        df.addColumn("Total");
        df.addColumn("Pago");
        df.addColumn("Cambio");
        df.addColumn("No. Paciente/Consulta");
        df.addColumn("Cajero nombre");
        df.addColumn("Cajero apellido");
                Criteria cr = s.createCriteria(FacturaExamen.class);
                cr.add(Restrictions.between("fecha",fechai,fechaf));
                Criteria crf = s.createCriteria(Pojo.FacturaConsulta.class);
                crf.add(Restrictions.between("fecha",fechai,fechaf));
                List<Pojo.FacturaExamen> listafe = cr.list();
                List<Pojo.FacturaConsulta> listafc = crf.list();
                List<Paciente> listap = d.Listar_Pacientes();
                List<Pojo.Cajero> listac = d.Listar_Cajero();
                List<Pojo.Consulta> listacons = d.Listar_Consulta();
                
                for(FacturaExamen fe : listafe){
                    for(Pojo.Cajero c : listac){
                        if(c.getIdCajero() == fe.getCajero().getIdCajero()){
                            for(Pojo.Paciente p : listap){
                                if(p.getIdPaciente() == fe.getPaciente().getIdPaciente()){
                                    String fila []= {String.valueOf(fe.getNumfactura()),String.valueOf( fe.getFecha()),String.valueOf(fe.getTotal()), String.valueOf(fe.getPago()),String.valueOf(fe.getCambio()), String.valueOf(p.getIdPaciente()), c.getNombre(),c.getApellido()};
                                    df.addRow(fila);
                                }
                            }
                        }
                    }
                }
                
                for(FacturaConsulta fc : listafc){
                    for(Pojo.Cajero c : listac){
                        if(c.getIdCajero() == fc.getCajero().getIdCajero()){
                            for(Pojo.Consulta co : listacons){
                                if(co.getIdConsulta() == fc.getConsulta().getIdConsulta()){
                                    String fila []= {String.valueOf(fc.getNumfactura()),String.valueOf( fc.getFecha()),String.valueOf(fc.getTotal()), String.valueOf(fc.getPago()),String.valueOf(fc.getCambio()),String.valueOf(co.getIdConsulta()),c.getNombre(),c.getApellido()};
                                    df.addRow(fila);
                                }
                            }
                        }
                    }
                }

                
                this.jTable1.setModel(df);
                
                
                
                    } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(this,"Formato yyyy-MM-dd HH:mm","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            VerFacturas c = new VerFacturas(sf);
            this.getDesktopPane().add(c);
            c.setMaximum(true);
            c.setVisible(true);
            this.dispose();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VerFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(this.jTable1.getSelectedRow()!= -1){
        int numfact = Integer.parseInt(String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0)));
        DAO d = new DAO(sf);
        List<FacturaExamen> listafe = d.ListarFacturaExamen();
        List<FacturaConsulta> listafc = d.ListarFacturaConsulta();
        List<DetalleFactpro> listadfp = d.ListarDetFactPro();
        List<DetalleFacturaEx> listadfe = d.ListarDetFactEx();
        
        FacturaExamen fe = null;
        FacturaConsulta fc = null;
        
        for(FacturaExamen factex : listafe){
        if(factex.getNumfactura()==numfact){fe = factex;}
        }
        
        for(FacturaConsulta factcon : listafc){
        if(factcon.getNumfactura() == numfact){fc = factcon;}
        }
        
        if(fe!=null){
        this.jTextArea1.setText("--Factura Externa--"+"\n"+"ID Factura Externa: "+fe.getIdFacturaex()+"\n");
        for(DetalleFacturaEx dfe : listadfe){
        if(dfe.getFacturaExamen().getIdFacturaex() == fe.getIdFacturaex()){
        this.jTextArea1.setText(this.jTextArea1.getText()+dfe.getCatalogoExamen().getNombre()+"----- U$"+String.valueOf(dfe.getCatalogoExamen().getPrecio())+"\n");
        }
        }
        for(DetalleFactpro dfp : listadfp){
        if(dfp.getFacturaExamen().getIdFacturaex() == fe.getIdFacturaex()){
        this.jTextArea1.setText(this.jTextArea1.getText()+dfp.getProcedimientosEspeciales().getNombre()+"----- U$"+String.valueOf(dfp.getProcedimientosEspeciales().getPrecio())+"\n"); 
        }
        }
        }
        
        
        else{
        this.jTextArea1.setText("--Factura Consulta--"+"\n"+"ID Factura Consulta: "+fc.getIdFactura()+"\n" +"ID Consulta: "+String.valueOf(fc.getConsulta().getIdConsulta())+"\n");
        }
        
        
        }
        
    }//GEN-LAST:event_jTable1MouseClicked
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
}
