package Pojo;
// Generated Jul 8, 2015 3:59:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private Integer idConsulta;
     private String descripcion;
     private Float precio;
     private Set diagnosticos = new HashSet(0);
     private Set detalleConsultas = new HashSet(0);

    public Consulta() {
    }

	
    public Consulta(String descripcion) {
        this.descripcion = descripcion;
    }
    public Consulta(String descripcion, Float precio, Set diagnosticos, Set detalleConsultas) {
       this.descripcion = descripcion;
       this.precio = precio;
       this.diagnosticos = diagnosticos;
       this.detalleConsultas = detalleConsultas;
    }
   
    public Integer getIdConsulta() {
        return this.idConsulta;
    }
    
    public void setIdConsulta(Integer idConsulta) {
        this.idConsulta = idConsulta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Set diagnosticos) {
        this.diagnosticos = diagnosticos;
    }
    public Set getDetalleConsultas() {
        return this.detalleConsultas;
    }
    
    public void setDetalleConsultas(Set detalleConsultas) {
        this.detalleConsultas = detalleConsultas;
    }




}


