package Pojo;
// Generated Aug 13, 2015 4:52:50 PM by Hibernate Tools 4.3.1



/**
 * DetalleFacturaEx generated by hbm2java
 */
public class DetalleFacturaEx  implements java.io.Serializable {


     private Integer idDetallefact;
     private CatalogoExamen catalogoExamen;
     private FacturaExamen facturaExamen;

    public DetalleFacturaEx() {
    }

    public DetalleFacturaEx(CatalogoExamen catalogoExamen, FacturaExamen facturaExamen) {
       this.catalogoExamen = catalogoExamen;
       this.facturaExamen = facturaExamen;
    }
   
    public Integer getIdDetallefact() {
        return this.idDetallefact;
    }
    
    public void setIdDetallefact(Integer idDetallefact) {
        this.idDetallefact = idDetallefact;
    }
    public CatalogoExamen getCatalogoExamen() {
        return this.catalogoExamen;
    }
    
    public void setCatalogoExamen(CatalogoExamen catalogoExamen) {
        this.catalogoExamen = catalogoExamen;
    }
    public FacturaExamen getFacturaExamen() {
        return this.facturaExamen;
    }
    
    public void setFacturaExamen(FacturaExamen facturaExamen) {
        this.facturaExamen = facturaExamen;
    }




}


