package Pojo;
// Generated Jul 8, 2015 6:12:54 AM by Hibernate Tools 4.3.1



/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private Integer idDetallefact;
     private CatalogoExamen catalogoExamen;
     private FacturaExamen facturaExamen;

    public DetalleFactura() {
    }

    public DetalleFactura(CatalogoExamen catalogoExamen, FacturaExamen facturaExamen) {
       this.catalogoExamen = catalogoExamen;
       this.facturaExamen = facturaExamen;
    }
   
    public Integer getIdDetallefact() {
        return this.idDetallefact;
    }
    
    public void setIdDetallefact(Integer idDetallefact) {
        this.idDetallefact = idDetallefact;
    }
    public CatalogoExamen getCatalogoExamen() {
        return this.catalogoExamen;
    }
    
    public void setCatalogoExamen(CatalogoExamen catalogoExamen) {
        this.catalogoExamen = catalogoExamen;
    }
    public FacturaExamen getFacturaExamen() {
        return this.facturaExamen;
    }
    
    public void setFacturaExamen(FacturaExamen facturaExamen) {
        this.facturaExamen = facturaExamen;
    }




}


