package Pojo;
// Generated Jul 5, 2015 1:46:36 PM by Hibernate Tools 4.3.1



/**
 * PadecimientoAm generated by hbm2java
 */
public class PadecimientoAm  implements java.io.Serializable {


     private Integer idPadecimientoam;
     private AlergiaMedicamento alergiaMedicamento;
     private Integer idPaciente;

    public PadecimientoAm() {
    }

	
    public PadecimientoAm(AlergiaMedicamento alergiaMedicamento) {
        this.alergiaMedicamento = alergiaMedicamento;
    }
    public PadecimientoAm(AlergiaMedicamento alergiaMedicamento, Integer idPaciente) {
       this.alergiaMedicamento = alergiaMedicamento;
       this.idPaciente = idPaciente;
    }
   
    public Integer getIdPadecimientoam() {
        return this.idPadecimientoam;
    }
    
    public void setIdPadecimientoam(Integer idPadecimientoam) {
        this.idPadecimientoam = idPadecimientoam;
    }
    public AlergiaMedicamento getAlergiaMedicamento() {
        return this.alergiaMedicamento;
    }
    
    public void setAlergiaMedicamento(AlergiaMedicamento alergiaMedicamento) {
        this.alergiaMedicamento = alergiaMedicamento;
    }
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }




}


