package Pojo;
// Generated Jul 8, 2015 3:59:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProcedimientosEspeciales generated by hbm2java
 */
public class ProcedimientosEspeciales  implements java.io.Serializable {


     private Integer idProc;
     private String nombre;
     private String descripcion;
     private float precio;
     private Set detalleFactpros = new HashSet(0);

    public ProcedimientosEspeciales() {
    }

    public ProcedimientosEspeciales(Integer idProc, String nombre, String descripcion, float precio) {
        this.idProc = idProc;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precio = precio;
    }

    public Integer getIdProc() {
        return idProc;
    }

    public void setIdProc(Integer idProc) {
        this.idProc = idProc;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public float getPrecio() {
        return precio;
    }

    public void setPrecio(float precio) {
        this.precio = precio;
    }

    public Set getDetalleFactpros() {
        return detalleFactpros;
    }

    public void setDetalleFactpros(Set detalleFactpros) {
        this.detalleFactpros = detalleFactpros;
    }

	
   



}


